SELECT  D.ADMCLICOD, D.ADMACCCOD, D.ADMAGRCOD, D.ADMAGRSFX,  
		D.ADMTRNTYP, AGMCUSFNM, AGMCUSLNM, ADMDISTYP, D.ADMDISCOD, SUM(D.ADMDISAMT) Amt,
		A.AGMPRGCOD, D.ADMPRDCOD, AGDPLNCOD,AGDPRDSTS PRDSTS, AGDTRMTIM TERM, O.AGDNWUSNA NewUsedNA,
		A.AGMPSTDAT, D.ADMPSTDAT, ADDR.AADREGION
--Select *
FROM I400DASQL.EFGAS400.SESCSEFG.SCAGRM A
							  
							  INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRDM D
										ON  a.AGMCLICOD = D.ADMCLICOD AND
										  a.AGMACCCOD = D.ADMACCCOD AND
										  a.AGMAGRCOD = D.ADMAGRCOD AND
										  a.AGMAGRSFX = D.ADMAGRSFX
							  

							  INNER JOIN I400DASQL.EFGAS400.SESCSEFG.AGDTA00 O
															ON a.AGMCLICOD = O.AGDCLICOD AND
																  a.AGMACCCOD = O.AGDACCCOD AND
																  a.AGMAGRCOD = O.AGDAGRCOD AND 
																  a.AGMAGRSFX = O.AGDAGRSFX AND 
																  D.ADMPRDCOD = O.AGDPRDCOD AND AGDPRDSTS IN ('INFORCE','CANCELLED','EXPIRED')

							  INNER JOIN ( SELECT  AADACCCOD, AADREGION FROM I400DASQL.EFGAS400.SESCSEFG.SCALTADR  R
											 INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRM S oN S.AGMACCCOD=R.AADACCCOD
											 WHERE AADADRTYP = 'PRIMARY'
											 Group By AADACCCOD, AADREGION
											) AS ADDR ON ADDR.AADACCCOD=AGMACCCOD
	  							  

							  WHERE ADMEFRTYN = 'Y' AND (ADMDISTYP='RESV' 
							                              OR ADMDISCOD IN ('ASGDFADM','BASEADMIN','CANCELFEE','CLAIMRESV','EFGADMIN','EXCINS','OKWARACT','RASADMIN','REPOF','ROADADMIN'))

							 
AND ADMAGRCOD IN
(
'             5195157',
'             1513239',
'             1516029',
'         90448000003')

GROUP BY
D.ADMCLICOD, D.ADMACCCOD, D.ADMAGRCOD, D.ADMAGRSFX, D.ADMPRDCOD, AGMCUSFNM,AGMCUSLNM, D.ADMTRNTYP,D.ADMDISTYP, D.ADMDISCOD,
A.AGMPRGCOD, AGDPLNCOD, AGDPRDSTS, AGDTRMTIM, AGDNWUSNA,
A.AGMPSTDAT, D.ADMPSTDAT,ADDR.AADREGION



