Select ProgramCode, PN.PRoductName, GrossContractCount=Sum(GrossContractCount), NetContractCount=Sum(NetContractCount), GrossReserves=Sum(GrossReserves), NetReserves=Sum(NetReserves), EarnedReserves=Sum(EarnedReserves), UnEarnedReserves=Sum(UnearnedReserves), ClaimsPaidCount=Sum(FS.ClaimsPaidCount), ClaimsPaid=Sum(ClaimsPaid) From FactSalesAggregate FS
INNER JOIN DimFourPartProductKey K ON K.KeyID=FS.FourPartKeyID 
INNER JOIN DimProductName PN ON PN.ProductNameID=FS.ProductNameID AND K.ProgramCode='SAN02'
Where PartnerID=4
GROUP BY K.ProgramCode, PN.PRoductName
ORDER BY K.ProgramCode, PN.PRoductName

Select ProgramCode, NetContractCount=Sum(NetContractCount), NetReserves=Sum(NetReserves), EarnedReserves=Sum(EarnedReserves), UnEarnedReserves=Sum(UnearnedReserves),
		 ClaimsPaidCount=Sum(FS.ClaimsPaidCount), ClaimsPaid=Sum(ClaimsPaid) ,
		 GrossReserves=Sum(GrossReserves),GrossContractCount=Sum(GrossContractCount)
	     
From FactSalesAggregate FS
INNER JOIN DimFourPartProductKey K ON K.KeyID=FS.FourPartKeyID AND (K.ProgramCode Like 'SAN%' OR  K.ProgramCode LIke 'SG%')
INNER JOIN DimProductName PN ON PN.ProductNameID=FS.ProductNameID 
GROUP BY K.ProgramCode
ORDER BY K.ProgramCode



Select ProgramCode, GrossContractCount=Sum(GrossContractCount), NetContractCount=Sum(NetContractCount), GrossReserves=Sum(GrossReserves), NetReserves=Sum(NetReserves), EarnedReserves=Sum(EarnedReserves), UnEarnedReserves=Sum(UnearnedReserves), ClaimsPaidCount=Sum(FS.ClaimsPaidCount), ClaimsPaid=Sum(ClaimsPaid) From FactSalesAggregate FS
INNER JOIN DimFourPartProductKey K ON K.KeyID=FS.FourPartKeyID AND K.ProgramCode='SAN02'
Where PartnerID=4
GROUP BY K.ProgramCode
ORDER BY K.ProgramCode

Select ProgramCode, GrossContractCount=Sum(GrossContractCount), NetContractCount=Sum(NetContractCount), GrossReserves=Sum(GrossReserves), NetReserves=Sum(NetReserves), 
	   EarnedReserves=Sum(EarnedReserves), UnEarnedReserves=Sum(UnearnedReserves), ClaimsPaidCount=Sum(FS.ClaimsPaidCount), ClaimsPaid=Sum(ClaimsPaid) 
From FactSalesAggregate FS
INNER JOIN DimFourPartProductKey K ON K.KeyID=FS.FourPartKeyID AND K.ProgramCode='SAN02'--AND (K.ProgramCode Like 'SAN%' OR  K.ProgramCode LIke 'SG%')
GROUP BY K.ProgramCode
ORDER BY K.ProgramCode


Select ProgramCode, ProductCode, PlanCode,  GrossContractCount=Sum(GrossContractCount), NetContractCount=Sum(NetContractCount), GrossReserves=Sum(GrossReserves), NetReserves=Sum(NetReserves), EarnedReserves=Sum(EarnedReserves), UnEarnedReserves=Sum(UnearnedReserves), ClaimsPaidCount=Sum(FS.ClaimsPaidCount), ClaimsPaid=Sum(ClaimsPaid) From FactSalesAggregate FS
INNER JOIN DimFourPartProductKey K ON K.KeyID=FS.FourPartKeyID AND K.ProgramCode='SAN02'
Where PartnerID=4
Group by ProgramCode, ProductCode, PlanCode
Order by ProgramCode, ProductCode, PlanCode
Select ProgramCode, ProductCode, PlanCode, GrossContractCount=Sum(GrossContractCount), NetContractCount=Sum(NetContractCount), GrossReserves=Sum(GrossReserves), NetReserves=Sum(NetReserves), 
	   EarnedReserves=Sum(EarnedReserves), UnEarnedReserves=Sum(UnearnedReserves), ClaimsPaidCount=Sum(FS.ClaimsPaidCount), ClaimsPaid=Sum(ClaimsPaid) 
From FactSalesAggregate FS
INNER JOIN DimFourPartProductKey K ON K.KeyID=FS.FourPartKeyID AND K.ProgramCode='SAN02'--AND (K.ProgramCode Like 'SAN%' OR  K.ProgramCode LIke 'SG%')
Group by ProgramCode, ProductCode, PlanCode
Order by ProgramCode, ProductCode, PlanCode

Select * From MasterProductMatrix where CPlan='SGLMPTOU'





SELECT * FROM I400DASQL.EFGAS400.SESCSEFG.SCAGRM A
INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRDM D
										ON  a.AGMCLICOD = D.ADMCLICOD AND
										  a.AGMACCCOD = D.ADMACCCOD AND
										  a.AGMAGRCOD = D.ADMAGRCOD AND
										  a.AGMAGRSFX = D.ADMAGRSFX
 INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM p
															ON a.AGMCLICOD = p.APVCLICOD AND
																  a.AGMACCCOD = p.APVACCCOD AND
																  a.AGMAGRCOD = p.APVAGRCOD AND
																  a.AGMAGRSFX = p.APVAGRSFX AND 
																  D.ADMPRDCOD = p.APVPRDCOD AND 
																  p.APVFLDCOD = '~MVPRDSTS' AND 
																  p.APVALPVAL IN('INFORCE','CANCELLED','EXPIRED')
 INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM PLN
															ON a.AGMCLICOD = PLN.APVCLICOD AND
																  a.AGMACCCOD = PLN.APVACCCOD AND
																  a.AGMAGRCOD = PLN.APVAGRCOD AND
																  a.AGMAGRSFX = PLN.APVAGRSFX AND 
																  D.ADMPRDCOD = PLN.APVPRDCOD AND 
																  PLN.APVFLDCOD = '~MVPLNCOD' AND PLN.apvflddsc NOT like 'Cov%'
		  --INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM TERM
				--											ON a.AGMCLICOD = TERM.APVCLICOD AND
				--												  a.AGMACCCOD = TERM.APVACCCOD AND
				--												  a.AGMAGRCOD = TERM.APVAGRCOD AND
				--												  a.AGMAGRSFX = TERM.APVAGRSFX AND 
				--												  D.ADMPRDCOD = TERM.APVPRDCOD AND 
				--												  TERM.APVFLDCOD = '~MVTRMTIM'
																  
							INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM V
															ON a.AGMCLICOD = V.APVCLICOD AND
																  a.AGMACCCOD = V.APVACCCOD AND
																  a.AGMAGRCOD = V.APVAGRCOD AND
																  a.AGMAGRSFX = V.APVAGRSFX AND 
																  D.ADMPRDCOD = V.APVPRDCOD AND 
																  V.APVFLDCOD = '~MVNWUSNA'
WHERE A.AGMAGRCOD IN   ('         90448000012',
						'         90448000004',
						'         90448000001',
						'         90448000009',
						'         90448000002')




Select GrossContractCount=Sum(GrossContractCount), NetContractCount=Sum(NetContractCount), GrossReserves=Sum(GrossReserves), NetReserves=Sum(NetReserves), 
	   EarnedReserves=Sum(EarnedReserves), UnEarnedReserves=Sum(UnearnedReserves), ClaimsPaidCount=Sum(FS.ClaimsPaidCount), ClaimsPaid=Sum(ClaimsPaid) 
From efgsales.dbo.FactSalesAggregate FS


Select sum(CH.AEPERNCM) FrOM StagingSales.[dbo].[ClaimSummaryHist] CH

Select sum(AEPERNCM) FROM I400DASQL.EFGAS400.SESCSEFG.SCAGREP 

Select Sum(AEP90DETM) FROM I400DASQL.EFGAS400.SESCSEFG.SCAGREP 





Select GrossContractCount=Sum(GrossContractCount), NetContractCount=Sum(NetContractCount), GrossReserves=Sum(GrossReserves), NetReserves=Sum(NetReserves), 
	   EarnedReserves=Sum(EarnedReserves), UnEarnedReserves=Sum(UnearnedReserves), ClaimsPaidCount=Sum(ClaimsPaidCount), ClaimsPaid=Sum(ClaimsPaid)  From FactSalesAggregate F
INNER JOIN DimFourPartProductKey K ON K.KeyID=F.FourPartKeyID Where ProgramCode Like 'TCH%'



Select * From FactSalesAggregate A (nolock)
LEFT JOIN DimAccount DA (nolock) ON DA.AccountID=A.AccountID
LEFT JOIN DimProductCategory PC (nolock) ON PC.ProductCategoryID=A.ProductCategoryID
LEFT JOIN DimProductType PT (nolock) ON PT.ProductTypeID=A.ProductTypeID
LEFT JOIN DimProductName PN (nolock) ON PN.ProductNameID=A.ProductNameID
LEFT JOIN DimCoverage CV (nolock) ON CV.CoverageID=A.CoverageID
LEFT JOIN DimPartner P (nolock) ON P.PartnerID=A.PartnerID
LEFT JOIN DimNationalAccount NA (nolock) ON NA.NationalAccountID=A.NationalAccountID
LEFT JOIN DimSalesManager SM (nolock) ON SM.SalesManagerID=A.SalesManagerID
LEFT JOIN DimPlan PL (nolock) ON PL.PlanID=A.PlanID
LEFT JOIN DimVehicleState VH (nolock) ON VH.VehicleStateID=A.VehicleStateID
LEFT JOIN DimTerms TM (nolock) ON TM.TermID=A.TermID
LEFT JOIN DimFourPartProductKey FPK (nolock) ON FPK.KeyID=A.FourPartKeyID
LEFT JOIN DimState ST (nolock) ON ST.StateID=A.StateID
WHERE DA.AccountID IS NULL OR PC.ProductCategoryID IS NULL OR PT.ProductTypeID IS NULL 
OR PN.ProductNameID IS NULL OR CV.CoverageID IS NULL OR P.PartnerID IS NULL
OR NA.NationalAccountID IS NULL OR NA.NationalAccountID IS NULL OR SM.SalesManagerID IS NULL 
OR PL.PlanID IS NULL OR VH.VehicleStateID IS NULL OR TM.TermID IS NULL OR  FPK.KeyID IS NULL
OR ST.StateID IS NULL


Select PartnerName, SalesManagerName, NationalAccountName, Sum(EarnedReserves) From FactSalesAggregate A
INNER JOIN DimPartner P ON P.PartnerID=A.PartnerID
INNER JOIN DimNationalAccount NA  ON NA.NationalAccountID=A.NationalAccountID
INNER JOIN DimSalesManager SM  ON SM.SalesManagerID=A.SalesManagerID
WHERE A.PartnerID <> 4
Group by PartnerName, SalesManagerName, NationalAccountName


Select count(*) From fActSalesAggregate2 --42409
Select count(*) From FactSales2  --706453

Select count(*) From FactSalesAggregate Where Period=20140331
Select count(*) From FactSales Where Period=20140331 --706453




Select count(*) From StagingSales.dbo.ClaimSummaryHist

Select Sum(EarnedReserves) From FactSales
Select Sum(EarnedReserves) From FactSalesAggregate


Select Sum(NetReserves), Sum(EarnedReserves), Sum(ClaimsPaid), Sum(ClaimsCount) ,Sum(ClaimsPaidITD), Sum(GrossContractCount), Sum(NetContractCount) From FactSalesAggregate2 Where Period=20140331
Select Sum(NetReserves), Sum(EarnedReserves), Sum(ClaimsPaid), Sum(ClaimsCount),Sum(ClaimsPaidITD),Sum(GrossContractCount), Sum(NetContractCount)  From FactSalesAggregate Where Period=20140331

Select Sum(PRDCHKAMT) From _Staging_LastPull_ClaimsHist Group By PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD
Select PRDPRTDAT, Sum(PRDCHKAMT) From _Staging_LastPull_ClaimsHist Group By PRDPRTDAT
Select Sum(AEPCLMCM), SUM(AEPCLMITD) From _Staging_LastPull_ClaimsummaryHist Group By AEPYRMON

Select sum(AEPCLMCM) FROM I400DASQL.EFGAS400.SESCSEFG.SCAGREP WHERE AEPYRMON=201403
Select sum(AEPCLMCM) FROM I400DASQL.EFGAS400.SESCSEFG.SCAGREP 
Select sum(AEPCLMITD) FROM I400DASQL.EFGAS400.SESCSEFG.SCAGREP WHERE AEPYRMON=201403

 94493824.76  (ITD)
504183712.10  (MCM)
509142762.78  (Really Non voided Payments, including 0 Payment DAte)
509105747.13  (Really Non voided Payments)
509153665.14

3723077.69
4494711.63


552973528.14

Select Sum(PRDCHKAMT), Count(Distinct PRDCLMTID) From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT BETWEEN 20140300 AND 20140400 --AND PRDCLMTID=0
AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  WHERE PRDPRTDAT BETWEEN 20140300 AND 20140400 AND PRDPAYSTS = 'V' Group by PRDPAYTID)
--AND PRDCLMTID NOT IN (SELECT PRDCLMTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  WHERE PRDPRTDAT < 20140300 Group by PRDCLMTID)
-- Claims Paid from Sum of all time AEPERNCM 580441749.59
-- Month of March AEPERNCM =                   5494632.29
-- Actual True Claims Paid Non Voided and those whose first payment was not previeousely process) 3386239.15 --5195 (Count)
4565035.89  (All March)
4144922.09  (Excluding Voided)
3386239.15  (Excluding Voided and Partially Paid in the past)

3723077

select count(distinct PRDCLMTID) From #tmp Where prdpaysts=1

6083  (All March)
5873  (Excluding Voided)
5195  (Excluding voided and partially paid in the past.)




Select Sum(PRDCHKAMT), Count(Distinct PRDCLMTID) From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT BETWEEN 20140300 AND 20140400 
AND PRDCLMTID NOT IN (SELECT PRDCLMTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  WHERE PRDPRTDAT BETWEEN 20140300 AND 20140400 AND PRDPAYSTS = 'V' Group by PRDCLMTID)



Select PRDCLMTID, count(*)  From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD Group by PRDCLMTID ORDER By count(*) Desc

Select * From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD Where PRDCLMTID = 93080366

--                                                                                                 239843.43


SELECT  PRDCLICOD,
		PRDACCCOD,
		PRDAGRCOD,
		PRDAGRSFX,
		PRDPRDCOD,
		PRDCLMTID,
		PRDCHKAMT=SUM(PRDCHKAMT),
		PRDPAYSTS,		
		PRDPRTDAT=MIN(PRDPRTDAT)

FROM I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
WHERE PRDPRTDAT BETWEEN 20140300 AND 20140400
GROUP BY 
PRDCLICOD,
PRDACCCOD,
PRDAGRCOD,
PRDAGRSFX,
PRDPRDCOD,
PRDCLMTID,
PRDPAYSTS

Select * From _Staging_LastPull_ClaimsHist Where PRDCLMTID=93071372


Select PRDCLMTID, count(Distinct PRDPAYTID), Sum(PRDCHKAMT), MIN(PRDPAYSTS), MAX(PRDPAYSTS)
FROM I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
WHERE PRDPRTDAT BETWEEN 20140200 AND 20140300 AND PRDCLMTID>0
GROUP BY PRDCLMTID Having count(*)>1
ORDER BY PRDCLMTID


Select * 
FROM I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P 
Where PRDCLMTID=93071372




SELECT  PRDCLICOD,
		PRDACCCOD,
		PRDAGRCOD,
		PRDAGRSFX,
		PRDPRDCOD,
		PRDCLMTID,
		PRDCHKAMT=SUM(PRDCHKAMT),
		PRDPAYSTS,		
		PRDPRTDAT=MIN(PRDPRTDAT)
		PRDPRTDATMAX=MAX(PRDPRTDAT)
FROM I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
INNER JOIN 
WHERE PRDPRTDAT>0 AND
PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' Group by PRDPAYTID)
AND PRDCLMTID > 0
AND PRDCHKAMT <> 0
GROUP BY 
PRDCLICOD,
PRDACCCOD,
PRDAGRCOD,
PRDAGRSFX,
PRDPRDCOD,
PRDCLMTID,
PRDPAYSTS
HAVING MIN(PRDPRTDAT)>20140300

Select Sum(PRDCHKAMT) From #tmp 


Select sum(AEPCLMCM) FROM I400DASQL.EFGAS400.SESCSEFG.SCAGREP WHERE AEPYRMON=201403
--   4494711.63
Select Sum(PRDCHKAMT)  From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT  BETWEEN 20140300 AND 20140400 
AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' Group by PRDPAYTID)
AND PRDCLMTID > 0
AND PRDCHKAMT <> 0
---- 4301037.53

Select Sum(PRDCHKAMT) From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT  BETWEEN 20140300 AND 20140400 
--   4565035.89
Select Sum(PRDCHKAMT) From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT  BETWEEN 20140300 AND 20140400 AND PRDCLMTID > 0
--   4301037.53

Select PRDCLMTID 



------------ Claim Count for the Period
---------------------------NEW CLAIMS --------

SELECT  PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID, PRDCHKAMT=SUM(PRDCHKAMT),
		PRDPAYSTS='1', PRDPRTDAT=MIN(PRDPRTDAT)		
		into #tmp
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT  BETWEEN 20140300 AND 20140331 
AND PRDCLMTID>0
AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' Group by PRDPAYTID)

AND PRDCLMTID NOT IN (SELECT PRDCLMTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPRTDAT < 20140300 GROUP BY PRDCLMTID )
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,PRDCLMTID

-------------------------------OLD CLAIMS PAID THIS PERIOD -------------------------------------------------------
INSERT #tmp (PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID,
		PRDCHKAMT,	PRDPAYSTS, PRDPRTDAT)		
SELECT  PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID, PRDCHKAMT=SUM(PRDCHKAMT),
		PRDPAYSTS, PRDPRTDAT=MIN(PRDPRTDAT)				
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT  BETWEEN 20140300 AND 20140331 
AND PRDCLMTID>0
AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' Group by PRDPAYTID)
AND PRDCLMTID IN (SELECT PRDCLMTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPRTDAT < 20140300 GROUP BY PRDCLMTID )
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,PRDCLMTID,PRDPAYSTS


Select TotalPaidClaims=Sum(PRDCHKAMT), NewPaidClaims=Sum(CASE WHEN PRDPAYSTS='1' Then PRDCHKAMT ELSE 0 END), OldPaidClaims=Sum(CASE WHEN PRDPAYSTS<>'1' Then PRDCHKAMT ELSE 0 END), TotalPaidClaims=Count(Distinct PRDCLMTID ), NewClaims=Count(Distinct CASE WHEN PRDPAYSTS='1' Then PRDCLMTID ELSE NULL END), OldClaims=Count(Distinct CASE WHEN PRDPAYSTS<>'1' Then PRDCLMTID ELSE NULL END) From #tmp
Select TotalPaidClaims=Sum(PRDCHKAMT), NewPaidClaims=Sum(CASE WHEN PRDPAYSTS='1' Then PRDCHKAMT ELSE 0 END), OldPaidClaims=Sum(CASE WHEN PRDPAYSTS<>'1' Then PRDCHKAMT ELSE 0 END), TotalPaidClaims=Count(Distinct PRDCLMTID ), NewClaims=Count(Distinct CASE WHEN PRDPAYSTS='1' Then PRDCLMTID ELSE NULL END), OldClaims=Count(Distinct CASE WHEN PRDPAYSTS<>'1' Then PRDCLMTID ELSE NULL END) From #tmp2
Select sum(AEPCLMCM) FROM I400DASQL.EFGAS400.SESCSEFG.SCAGREP WHERE AEPYRMON=201403
------------ SIMPLE NEW CLAIM COUNT FOR PERIOD------------------------------------------
SELECT  OldClaimCount=Count(Distinct PRDCLMTID), Payment=SUM(PRDCHKAMT)
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT  BETWEEN 20140300 AND 20140331 
AND PRDCLMTID>0
AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' Group by PRDPAYTID)
AND PRDCLMTID IN (SELECT PRDCLMTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPRTDAT < 20140300 GROUP BY PRDCLMTID )

------------ SIMPLE OLD CLAIM COUNT FOR PERIOD------------------------------------------
SELECT  NewClaimCount=Count(Distinct PRDCLMTID), Payment=SUM(PRDCHKAMT)
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
WHERE PRDPRTDAT  BETWEEN 20140300 AND 20140331 
AND PRDCLMTID>0
AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' Group by PRDPAYTID)
AND PRDCLMTID NOT IN (SELECT PRDCLMTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPRTDAT < 20140300 GROUP BY PRDCLMTID )
----------------------------------------------------------------------------------------
Truncate Table _Staging_LastPull_ClaimsHist
INSERT _Staging_LastPull_ClaimsHist
		(PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID,
		PRDCHKAMT,	PRDPAYSTS, PRDPRTDAT)
SELECT  PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID, PRDCHKAMT=SUM(PRDCHKAMT),
		PRDPAYSTS='1', PRDPRTDAT=MIN(PRDPRTDAT)		
		
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P


WHERE PRDPRTDAT BETWEEN 19000000 AND 20140400
AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND 
PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,PRDCLMTID

-------------------------------OLD CLAIMS PAID THIS PERIOD -------------------------------------------------------
INSERT _Staging_LastPull_ClaimsHist (PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID,
		PRDCHKAMT,	PRDPAYSTS, PRDPRTDAT)		
SELECT  PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID, PRDCHKAMT=SUM(PRDCHKAMT),
		PRDPAYSTS, PRDPRTDAT=MIN(PRDPRTDAT)				
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
WHERE PRDPRTDAT  BETWEEN 20140300 AND 20140331 
AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND PRDPRTDAT>0
AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
AND PRDCLMTID IN (SELECT PRDCLMTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPRTDAT < 20140300 AND PRDPAYTYP='CL' AND PRDCLMTID>0 GROUP BY PRDCLMTID )
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,PRDCLMTID,PRDPAYSTS

---------------------------------------------------------------------------------------------------------------------

--Select count(*) From _Staging_LastPull_ClaimsHist--998797
Select * From _Staging_LastPull_ClaimsHist H Where H.PRDCLMTID=0 OR PRDPRTDAT=0
Select * From delete _Staging_LastPull_ClaimsHist Where PRDPRTDAT>20140000

Select C.DateID, H.* From _Staging_LastPull_ClaimsHist H 
INNER JOIN Calendar C ON Left(6, C.DateID)=Left(6, H.PRDPRTDAT)
WHERE H.PRDPRTDAT>20140000

UPDATE _Staging_LastPull_ClaimsHist 
SET PRDCLICOD=LTRIM(RTRIM(PRDCLICOD)),
	PRDACCCOD=LTRIM(RTRIM(PRDACCCOD)),
	PRDAGRCOD=LTRIM(RTRIM(PRDAGRCOD)),
	PRDAGRSFX=LTRIM(RTRIM(PRDAGRSFX)),
	PRDPRDCOD=LTRIM(RTRIM(PRDPRDCOD))


Select Count(*),  Sum(PRDCHKAMT) From _Staging_LastPull_ClaimsHist CH 
INNER JOIN DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
WHERE A.AgreementID IS NULL
Group by 
PRDCLICOD,
PRDACCCOD,
PRDAGRCOD,
PRDAGRSFX,
PRDPRDCOD

986919  506408321.91   -- All agreements accounted
746        253677.73   -- Agreemnts don't exist
----------------------
987665  506661999.64


Select count(*) From I400DASQL.EFGAS400.SESCSEFG.SCAGRM A



Select * From DimAgreement Where SourceAGRCOD like '%151000%'

Select Sum(PRDCHKAMT), count(*) From _Staging_LastPull_ClaimsHist 
504183712.10 -- From Earning MOnthly As of April

987661 -- 4 Claims missing for not having an agreement? How many?
506661904.64 --



SELECT  PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID, PRDCHKAMT=SUM(PRDCHKAMT),
		PRDPAYSTS='1', PRDPRTDAT=MIN(PRDPRTDAT)		

SELECT PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD
into #tmpAgrAll
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
--INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRM A 
--		ON A.AGMCLICOD=PRDCLICOD AND
--		   A.AGMACCCOD=PRDACCCOD AND
--		   A.AGMAGRCOD=PRDAGRCOD AND
--		   A.AGMAGRSFX=PRDAGRSFX 
WHERE PRDPRTDAT BETWEEN 19000000 AND 20140400
AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND 
PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD

SELECT PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD
into #tmpAgr2
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRM A 
		ON A.AGMCLICOD=PRDCLICOD AND
		   A.AGMACCCOD=PRDACCCOD AND
		   A.AGMAGRCOD=PRDAGRCOD AND
		   A.AGMAGRSFX=PRDAGRSFX 
 INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRDM D
										ON  a.AGMCLICOD = D.ADMCLICOD AND
										  a.AGMACCCOD = D.ADMACCCOD AND
										  a.AGMAGRCOD = D.ADMAGRCOD AND
										  a.AGMAGRSFX = D.ADMAGRSFX
WHERE PRDPRTDAT BETWEEN 19000000 AND 20140400
AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND 
PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD



SELECT PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,AGDPRDSTS
into #tmpAgr5
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRM A 
		ON A.AGMCLICOD=PRDCLICOD AND
		   A.AGMACCCOD=PRDACCCOD AND
		   A.AGMAGRCOD=PRDAGRCOD AND
		   A.AGMAGRSFX=PRDAGRSFX 
 INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRDM D
										ON  a.AGMCLICOD = D.ADMCLICOD AND
										  a.AGMACCCOD = D.ADMACCCOD AND
										  a.AGMAGRCOD = D.ADMAGRCOD AND
										  a.AGMAGRSFX = D.ADMAGRSFX
INNER JOIN I400DASQL.EFGAS400.SESCSEFG.AGDTA00 O
															ON a.AGMCLICOD = O.AGDCLICOD AND
																  a.AGMACCCOD = O.AGDACCCOD AND
																  a.AGMAGRCOD = O.AGDAGRCOD AND 
																  a.AGMAGRSFX = O.AGDAGRSFX AND 
																  D.ADMPRDCOD = O.AGDPRDCOD --AND AGDPRDSTS IN ('INFORCE','CANCELLED','EXPIRED')
WHERE PRDPRTDAT BETWEEN 19000000 AND 20140400
AND ADMEFRTYN = 'Y' AND (ADMDISTYP='RESV' 
OR ADMDISCOD IN ('ASGDFADM','BASEADMIN','CANCELFEE','CLAIMRESV','EFGADMIN','EXCINS','OKWARACT','RASADMIN','REPOF','ROADADMIN'))
AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND 
PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,AGDPRDSTS


SELECT PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,AGDPRDSTS
into #tmpAgr6
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRM A 
		ON A.AGMCLICOD=PRDCLICOD AND
		   A.AGMACCCOD=PRDACCCOD AND
		   A.AGMAGRCOD=PRDAGRCOD AND
		   A.AGMAGRSFX=PRDAGRSFX 
INNER JOIN I400DASQL.EFGAS400.SESCSEFG.AGDTA00 O
															ON a.AGMCLICOD = O.AGDCLICOD AND
																  a.AGMACCCOD = O.AGDACCCOD AND
																  a.AGMAGRCOD = O.AGDAGRCOD AND 
																  a.AGMAGRSFX = O.AGDAGRSFX
WHERE PRDPRTDAT BETWEEN 19000000 AND 20140400
AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND 
PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,AGDPRDSTS

------------------------------------ P V M -------------------------------------

SELECT PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,V.APVFLDCOD
into #tmpAgrPVMNewUsed
From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRM A 
		ON A.AGMCLICOD=PRDCLICOD AND
		   A.AGMACCCOD=PRDACCCOD AND
		   A.AGMAGRCOD=PRDAGRCOD AND
		   A.AGMAGRSFX=PRDAGRSFX 
 INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRDM D
										ON  a.AGMCLICOD = D.ADMCLICOD AND
										  a.AGMACCCOD = D.ADMACCCOD AND
										  a.AGMAGRCOD = D.ADMAGRCOD AND
										  a.AGMAGRSFX = D.ADMAGRSFX
 --INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM pvm
	--														ON a.AGMCLICOD = pvm.APVCLICOD AND
	--															  a.AGMACCCOD = pvm.APVACCCOD AND
	--															  a.AGMAGRCOD = pvm.APVAGRCOD AND
	--															  a.AGMAGRSFX = pvm.APVAGRSFX AND 
	--															  D.ADMPRDCOD = pvm.APVPRDCOD AND 
	--															  pvm.APVFLDCOD = '~MVPRDSTS' AND 
	--															  pvm.APVALPVAL IN('INFORCE','CANCELLED','EXPIRED')
							  --INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM PLN
									--						ON a.AGMCLICOD = PLN.APVCLICOD AND
									--							  a.AGMACCCOD = PLN.APVACCCOD AND
									--							  a.AGMAGRCOD = PLN.APVAGRCOD AND
									--							  a.AGMAGRSFX = PLN.APVAGRSFX AND 
									--							  D.ADMPRDCOD = PLN.APVPRDCOD AND 
									--							  PLN.APVFLDCOD = '~MVPLNCOD'
							  --INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM TERM
									--						ON a.AGMCLICOD = TERM.APVCLICOD AND
									--							  a.AGMACCCOD = TERM.APVACCCOD AND
									--							  a.AGMAGRCOD = TERM.APVAGRCOD AND
									--							  a.AGMAGRSFX = TERM.APVAGRSFX AND 
									--							  D.ADMPRDCOD = TERM.APVPRDCOD AND 
									--							  TERM.APVFLDCOD = '~MVTRMTIM'
																  
							INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM V
															ON a.AGMCLICOD = V.APVCLICOD AND
																  a.AGMACCCOD = V.APVACCCOD AND
																  a.AGMAGRCOD = V.APVAGRCOD AND
																  a.AGMAGRSFX = V.APVAGRSFX AND 
																  D.ADMPRDCOD = V.APVPRDCOD AND 
																  V.APVFLDCOD = '~MVNWUSNA'		
WHERE PRDPRTDAT BETWEEN 19000000 AND 20140400
AND ADMEFRTYN = 'Y' AND (ADMDISTYP='RESV' 
OR ADMDISCOD IN ('ASGDFADM','BASEADMIN','CANCELFEE','CLAIMRESV','EFGADMIN','EXCINS','OKWARACT','RASADMIN','REPOF','ROADADMIN'))
AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND 
PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
                      WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,V.APVFLDCOD







UPDATE #tmpAgr4
SET PRDCLICOD=LTRIM(RTRIM(PRDCLICOD)),
	PRDACCCOD=LTRIM(RTRIM(PRDACCCOD)),
	PRDAGRCOD=LTRIM(RTRIM(PRDAGRCOD)),
	PRDAGRSFX=LTRIM(RTRIM(PRDAGRSFX)),
	PRDPRDCOD=LTRIM(RTRIM(PRDPRDCOD))



UPDATE #tmpAgrPVM
SET PRDCLICOD=LTRIM(RTRIM(PRDCLICOD)),
	PRDACCCOD=LTRIM(RTRIM(PRDACCCOD)),
	PRDAGRCOD=LTRIM(RTRIM(PRDAGRCOD)),
	PRDAGRSFX=LTRIM(RTRIM(PRDAGRSFX)),
	PRDPRDCOD=LTRIM(RTRIM(PRDPRDCOD)),
	AGDPRDSTS=LTRIM(RTRIM(AGDPRDSTS))






Select * From #tmpAgr ch

Select CH.PRDCLICOD, CH.PRDACCCOD, CH.PRDAGRCOD, CH.PRDAGRSFX, CH.PRDPRDCOD From #tmpAgrAll ch
inner join _Staging_LastPull_ClaimsHist sp 
on sp.PRDCLICOD=ch.PRDCLICOD
and sp.PRDACCCOD=ch.PRDACCCOD
and sp.PRDAGRCOD=ch.PRDAGRCOD
and sp.PRDAGRSFX=ch.PRDAGRSFX
and sp.PRDPRDCOD=ch.PRDPRDCOD
left join  DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
Where A.AgreementID is null 
Group  by CH.PRDCLICOD, CH.PRDACCCOD, CH.PRDAGRCOD, CH.PRDAGRSFX, CH.PRDPRDCOD



Select count(*) From #tmpAgr

Select * from #tmpAgrAll a
Left Join #tmpAgr  ta  ON A.PRDCLICOD =ta.PRDCLICOD AND
		   A.PRDACCCOD =ta.PRDACCCOD AND
		   A.PRDAGRCOD =ta.PRDAGRCOD AND
		   A.PRDAGRSFX =ta.PRDAGRSFX 
Where ta.PRDAcccod is null


Select Alls=count(*) From #tmpAgrAll ch
left join  DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
Where A.AgreementID is null 

Select WithAgr=count(*) From #tmpAgr ch
left join  DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
Where A.AgreementID is null 

Select withDisb=count(*) From #tmpAgr2 ch
left join  DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
Where A.AgreementID is null 

Select withPrd=count(*) From #tmpAgr3 ch
left join  DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
Where A.AgreementID is null 

Select withPrdDisFilter=count(*) From #tmpAgr4 ch
left join  DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
Where A.AgreementID is null 



Select AGDPRDSTS, withPrdDisFilter=count(*) From #tmpAgr5 ch
left join  DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
Where A.AgreementID is null 
Group by AGDPRDSTS


Select ch.AGDPRDSTS, AgreementCount=count(DISTINCT CH.prdcliCOD+cH.PRDACCCOD+CH.PRDAGRCOD+CH.PRDAGRSFX+CH.PRDPRDCOD), ClaimCount=COUNT(dISTINCT C.PRDCLMTID), ClaimPayment=sUM(C.PRDCHKAMT) 
From #tmpAgr6 ch
inner join _Staging_LastPull_ClaimsHist c ON
				CH.PRDCLICOD=c.PRDCLICOD AND
				CH.PRDACCCOD=C.PRDACCCOD AND
				CH.PRDAGRCOD=C.PRDAGRCOD AND
				CH.PRDAGRSFX=c.PRDAGRSFX AND
				CH.PRDPRDCOD=c.PRDPRDCOD 
left join #tmpAgrPVMNewUsed tt on tt.PRDCLICOD=c.PRDCLICOD AND
				tt.PRDACCCOD=C.PRDACCCOD AND
				tt.PRDAGRCOD=C.PRDAGRCOD AND
				tt.PRDAGRSFX=c.PRDAGRSFX AND
				tt.PRDPRDCOD=c.PRDPRDCOD
left join  DimAgreement A
			ON  CH.PRDCLICOD=A.SourceCLICOD AND
				CH.PRDACCCOD=A.SourceACCCOD AND
				CH.PRDAGRCOD=A.SourceAGRCOD AND
				CH.PRDAGRSFX=A.SourceAGRSFX AND
				CH.PRDPRDCOD=A.SourcePRDCOD 
Where A.AgreementID is null And ch.AGDPRDSTS NOT IN ('DENIED', 'SUSPENDED','VOID') And tt.PRDCLICOD IS NULL

Group by ch.AGDPRDSTS

-----------------

Select ch.AGDPRDSTS, AgreementCount=count(DISTINCT CH.prdcliCOD+cH.PRDACCCOD+CH.PRDAGRCOD+CH.PRDAGRSFX+CH.PRDPRDCOD), ClaimCount=COUNT(dISTINCT C.PRDCLMTID), ClaimPayment=sUM(C.PRDCHKAMT) 
--Select DISTINCT CH.PRDCliCOD, cH.PRDACCCOD, CH.PRDAGRCOD, CH.PRDAGRSFX, CH.PRDPRDCOD, C.PRDCLMTID, C.PRDCHKAMT, C.PRDPRTDAT, C.PRDCliCOD, c.PRDACCCOD, C.PRDAGRCOD, C.PRDAGRSFX, C.PRDPRDCOD
From _Staging_LastPull_ClaimsHist c
left join #tmpAgr6 ch ON
				CH.PRDCLICOD=c.PRDCLICOD AND
				CH.PRDACCCOD=C.PRDACCCOD AND
				CH.PRDAGRCOD=C.PRDAGRCOD AND
				CH.PRDAGRSFX=c.PRDAGRSFX AND
				CH.PRDPRDCOD=c.PRDPRDCOD 

--left join  DimAgreement A
--			ON  c.PRDCLICOD=A.SourceCLICOD AND
--				c.PRDACCCOD=A.SourceACCCOD AND
--				c.PRDAGRCOD=A.SourceAGRCOD AND
--				c.PRDAGRSFX=A.SourceAGRSFX AND
--				c.PRDPRDCOD=A.SourcePRDCOD 

Where ch.PRDACCCOD is null --ch.AGDPRDSTS NOT IN ('DENIED', 'SUSPENDED','VOID') 
Order by CH.prdcliCOD, cH.PRDACCCOD, CH.PRDAGRCOD, CH.PRDAGRSFX, CH.PRDPRDCOD, C.PRDCLMTID, C.PRDCHKAMT, C.PRDPRTDAT
Group by ch.AGDPRDSTS 


Select * FRom I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
Where PRDCLMTID IN (92687235,
92687267,
92687484,
92687746)


Select * From DimAccount Where EFGAccountCode='0000025501'


select distinct APVALPVAL 
FROM I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM 
WHERE APVFLDCOD ='~MVCLSCOD' 

Select  APVFLDCOD, APVFLDDSC, APVALPVAL, APVALPNUm, APVNUMVAL, *
FROM I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM 
WHERE APVFLDCOD ='~MVSTRUSG' 



Select  APVFLDCOD, APVFLDDSC, APVALPVAL, APVALPNUm, APVNUMVAL, *
FROM I400DASQL.EFGAS400.SESCSEFG.SCAGRPVM 
WHERE APVFLDCOD ='~MVDEDAMT' 
AND APVALPVAL>50


Categories (Dimensions):
           SaleYear
		       - AgreementPostedDate
		   Class  (All, Class1-8, NA)
		        '~MVCLSCOD' [~MVAWD0,~MVAWD123]
		   Plan   (New/Used)
		   Coverage ([1 Thru 4,10,11] [6 THRU 12], Platinum1-2,  Gold 1-8, LPLW 1-3, MAJOR, Major 1-4, Major 1-4 Certified, Major 5-12 PowerTrain Wrap, etc.)
		             '~MVCOVGRP'
		   Deductable $100 
					'~MVDEDAMT'
		   TERM (Years/Mileage) 1/1000, 3/3000, 6/6000...120/300000 -- Transformed Dimension
		             '~MVTRMTIM'/'~MVTRMUSG'
		   OdometerBand  [1 to 12000], [12001 to 24000], [24001 to 36000].... [120001 to 150000], [Over 150,000] ---Transformed Dimension
		   '~MVSTRUSG'
		   OdometerBand + Coverage e.g.  [Over 150,000]          [Total Plus C]
		   Vehicle Make  (Acura, Audi, BMW, Buick, Cadillac, Chevrolet, Default, Dodge, Eagle, FIAT, HONDA, TOYOTA.....)
		   '~MVITMMAK'
		   VehicleYear (1987...2014)
		   Contract Status (Active, Canceled, Expired, Terminated)

Measures:
               #Contracts, GrossReserves, AvgPremium, NetReserves, EarnedReserves, PctEarned, #Claims, Claims$, AvgPaidClaim, ClaimFreq, LossRatio


			   Select * From ETL_Log Order by ETLRunDateTime desc
		    

------------------------------------------------------------- CLAIMS


		SELECT  P.PRDCLICOD, P.PRDACCCOD, P.PRDAGRCOD, P.PRDAGRSFX, P.PRDPRDCOD, P.PRDCLMTID, PRDCHKAMT=Sum(P.PRDCHKAMT),
				PRDPAYSTS='1', MIN(LEFT(P.PRDPRTDAT,6)), AllClaims.PRDPRTDAT
		From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
		INNER JOIN (
					 SELECT PRDCLICOD=PRDCLICOD, PRDACCCOD=PRDACCCOD, PRDAGRCOD=PRDAGRCOD, PRDAGRSFX=PRDAGRSFX, 
							PRDPRDCOD=PRDPRDCOD, PRDCLMTID=PRDCLMTID, PRDPRTDAT=LEFT(PRDPRTDAT,6), Amt=Sum(PRDCHKAMT)
					 From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  					 
					 WHERE PRDPAYTYP IN ('CL','CN') AND PRDCHKAMT<>0 AND PRDPRTDAT>0 AND PRDPRTDAT <= 20140331 AND
					  PRDAGRCOD='         56889150506' AND
						PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
														  WHERE PRDPAYSTS = 'V' Group by PRDPAYTID )
					 GROUP BY PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD,PRDCLMTID, LEFT(PRDPRTDAT,6)
					) AS AllClaims ON AllClaims.PRDCLICOD=P.PRDCLICOD aND AllClaims.PRDACCCOD=P.PRDACCCOD AND AllClaims.PRDAGRCOD=P.PRDAGRCOD
					AND AllClaims.PRDAGRSFX=P.PRDAGRSFX AND AllClaims.PRDPRDCOD=P.PRDPRDCOD AND AllClaims.PRDCLMTID=P.PRDCLMTID 
					AND LEFT(P.PRDPRTDAT,6)=AllClaims.PRDPRTDAT	-- USE THIS FOR ALL DATA
		--WHERE P.PRDPRTDAT BETWEEN 20140301 AND 20140331 
		WHERE P.PRDPRTDAT>0
		AND P.PRDAGRCOD='         56889150506' 
		AND P.PRDPAYTYP IN ('CL','CN') AND P.PRDCHKAMT<>0 AND 
		P.PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
							  WHERE PRDPAYSTS = 'V' Group by PRDPAYTID)
		GROUP BY P.PRDCLICOD,P.PRDACCCOD,P.PRDAGRCOD,P.PRDAGRSFX,P.PRDPRDCOD,P.PRDCLMTID, AllClaims.PRDPRTDAT


		SELECT PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD,PRDCLMTID, ClaimPeriod=PRDPRTDAT, Sum(PRDCHKAMT), AmountPeriod=MaxDate
		FROM (
       SELECT  P.PRDCLICOD, P.PRDACCCOD, P.PRDAGRCOD, P.PRDAGRSFX, P.PRDPRDCOD, P.PRDCLMTID, PRDCHKAMT=Sum(P.PRDCHKAMT),
				PRDPAYSTS='1', MaxDate=MIN(LEFT(P.PRDPRTDAT,6)), AllClaims.PRDPRTDAT
		From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
		INNER JOIN (
					 SELECT PRDCLICOD=PRDCLICOD, PRDACCCOD=PRDACCCOD, PRDAGRCOD=PRDAGRCOD, PRDAGRSFX=PRDAGRSFX, 
							PRDPRDCOD=PRDPRDCOD, PRDCLMTID=PRDCLMTID, PRDPRTDAT=LEFT(PRDPRTDAT,6), Amt=Sum(PRDCHKAMT)
					 From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  					 
					 WHERE PRDPAYTYP IN ('CL','CN') AND PRDCHKAMT<>0 AND PRDPRTDAT>0 AND PRDPRTDAT <= 20140331 AND
					  PRDAGRCOD='         56889150506' AND
						PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
														  WHERE PRDPAYSTS = 'V' Group by PRDPAYTID )
					 GROUP BY PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD,PRDCLMTID, LEFT(PRDPRTDAT,6)
					) AS AllClaims ON AllClaims.PRDCLICOD=P.PRDCLICOD aND AllClaims.PRDACCCOD=P.PRDACCCOD AND AllClaims.PRDAGRCOD=P.PRDAGRCOD
					AND AllClaims.PRDAGRSFX=P.PRDAGRSFX AND AllClaims.PRDPRDCOD=P.PRDPRDCOD AND AllClaims.PRDCLMTID=P.PRDCLMTID 
					--AND LEFT(P.PRDPRTDAT,6)=AllClaims.PRDPRTDAT	-- USE THIS FOR ALL DATA
		WHERE P.PRDPRTDAT BETWEEN 20140301 AND 20140331 
		--WHERE P.PRDPRTDAT>0
		AND P.PRDAGRCOD='         56889150506' 
		AND P.PRDPAYTYP IN ('CL','CN') AND P.PRDCHKAMT<>0 AND 
		P.PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
							  WHERE PRDPAYSTS = 'V' Group by PRDPAYTID)
		GROUP BY P.PRDCLICOD,P.PRDACCCOD,P.PRDAGRCOD,P.PRDAGRSFX,P.PRDPRDCOD,P.PRDCLMTID, AllClaims.PRDPRTDAT
		) AS Claims
		GROUP BY PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD,PRDCLMTID, PRDPRTDAT, MaxDate
		   
		   
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt) from FactSales with (nolock) Where Period=20140331 --5468,5307--5744		   		   	   
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt), Sum(CLMSrcAmtITD) from FactSalesAggregate with (nolock) Where Period=20140331 --5468,5307--5744		   		   	   
		   Select count(Distinct PRDCLMTID) , Sum(PRDCHKAMT),  Sum(CASE WHEN PRDPRTDATMIN=20140331 THEN PRDCHKAMT ELSE 0 END) FROM _Staging_LastPull_ClaimsHist2
		   Select count(Distinct PRDCLMTID) , Sum(PRDCHKAMT),  Sum(CASE WHEN PRDPRTDATMIN=20140331 THEN PRDCHKAMT ELSE 0 END) FROM _Staging_LastPull_ClaimsHist3
		   Select count(Distinct PRDCLMTID) , Sum(PRDCHKAMT),  Sum(CASE WHEN PRDPRTDATMIN=20140331 THEN PRDCHKAMT ELSE 0 END) FROM _Staging_LastPull_ClaimsHist
		   WHERE PRDPRTDATMIN=20140331		   	   	   
		   
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt) from FactSales2 ----------THIS IS FROM PREVIOUS FULL RUN
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt), Sum(CLMSrcAmtITD) from FactSalesAggregate2 -- THIS IS FROM PREVIOUS FULL RUN		   
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt), Sum(CLMSrcAmtITD) From FactSalesAggregate (nolock) where period=20140331
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt) from FactSales3 ----------THIS IS FROM LAST FULL RUN
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt), Sum(CLMSrcAmtITD) from FactSalesAggregate3 -- THIS IS FROM LAST FULL RUN

		   
		   


		   
		   Select count(*) , Sum(PRDCHKAMT) FROM _Staging_LastPull_ClaimsHist2 
		   
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt), Sum(CLMSrcAmtITD)  From FactSalesAggregate2 		   

		   Select count(Distinct PRDCLMTID) , Sum(PRDCHKAMT),  Sum(CASE WHEN PRDPRTDATMIN=20140331 THEN PRDCHKAMT ELSE 0 END) FROM _Staging_LastPull_ClaimsHist
		   Select sum(ClaimsCount), Sum(ClaimsPaidCount), Sum(CLMSrcAmt), Sum(CLMSrcAmtITD) From FactSalesAggregate (nolock) where period=20140331



		   INSERT _Staging_LastPull_ClaimsHist (PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID,
				PRDCHKAMT,	PRDPAYSTS, PRDPRTDAT)		

		Select Count(distinct PRDCLMTID) From 
		-- SELECT * FROM
		(
		SELECT  PRDCLICOD, PRDACCCOD, PRDAGRCOD, PRDAGRSFX, PRDPRDCOD, PRDCLMTID, PRDCHKAMT=SUM(PRDCHKAMT),
				sts=MAX(PRDPAYSTS), PRDPRTDAT=MIN(PRDPRTDAT)				
		From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD P
		WHERE PRDPRTDAT  > 0 AND PRDPRTDAT <= 20140331 AND PRDPRTDAT>=20140301
		AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND PRDCHKAMT<>0 --AND  PRDCLMTID=93087008
		AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
							  WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
		AND PRDCLMTID NOT IN (
								SELECT Distinct PRDCLMTID FROM I400DASQL.EFGAS400.SESCSEFG.SCPAYRD 
								WHERE 	PRDPRTDAT<=	20140228 
								AND PRDPAYTYP='CL' AND PRDCLMTID>0 AND  PRDCHKAMT<>0
								AND PRDPAYTID NOT IN (SELECT PRDPAYTID From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  
								WHERE PRDPAYSTS = 'V' AND PRDPAYTYP='CL' AND PRDCLMTID>0 Group by PRDPAYTID)
							 )	  		
		GROUP BY PRDCLICOD,PRDACCCOD,PRDAGRCOD,PRDAGRSFX,PRDPRDCOD,PRDCLMTID) As tabl
		WHERE PRDPRTDAT BETWEEN 20140301 AND 20140331 

		Select * From I400DASQL.EFGAS400.SESCSEFG.SCPAYRD  WHERE PRDCLMTID=93087008

		
		Select 4308+692


		   5469	5469	3604164.25
		   sp_whoisactive

		   Select Period, GrossContractCount=count(GrossContractCount), NetReserves=Sum(NetReserves), NetReservesITD=sum(NetReservesITD), GrossReserves=Sum(GrossReserves), GrossReservesITD=Sum(GrossReservesITD), EarnedReserves=Sum(EarnedReserves), EarnedReservesITD=Sum(EarnedReservesITD), ClaimsCount=Sum(ClaimsCount), ClaimsCountITD=Sum(ClaimsCountITD), ClaimsPaid=Sum(ClaimsPaid), ClaimsPaidITD=Sum(ClaimsPaidITD) From FactSalesAggregate with (nolock) 
		   Where FourPartKeyID IN (Select KeyID From DimFourPartProductKey  Where ProgramCode in ('APP06', 'SAN02'))
		   Group by Period Order by Period desc

		   Sp_whoisactive


		   