Select AGMCLICOD, AGMACCCOD, AGMAGRCOD, AGMAGRSFX, AGMPSTDAT, ADMPSTDAT into AGR2 FROM I400DASQL.EFGAS400.SESCSEFG.SCAGRM AG
INNER JOIN I400DASQL.EFGAS400.SESCSEFG.SCAGRDM D ON AG.AGMCLICOD=D.ADMCLICOD 
and AG.AGMACCCOD=D.ADMACCCOD and AG.AGMAGRCOD=D.ADMAGRCOD and AG.AGMAGRSFX=D.ADMAGRSFX
Where ADMPSTDAT > 20120101
GROUP BY AGMCLICOD, AGMACCCOD, AGMAGRCOD, AGMAGRSFX, AGMPSTDAT, ADMPSTDAT



UPDATE D SET AGMPSTDAT=AG.AGMPSTDAT 
--Select ADMPSTDAT, AG.AGMPSTDAT 
--SELECT MAX(ADMPSTDAT), MAX(AG.AGMPSTDAT)
FROM dbo.SalesTier1YTD_BU D
INNER JOIN AGR AG on AG.AGMCLICOD=D.ADMCLICOD AND AG.AGMACCCOD=D.ADMACCCOD and AG.AGMAGRCOD=D.ADMAGRCOD and AG.AGMAGRSFX=D.ADMAGRSFX
WHERE ADMPSTDAT>0 

SELECT * FROM dbo.SalesTier1_BU

SELECT Distinct ADMPSTDAT, AGMPSTDAT FROM dbo.SalesTier1YTD_BU
WHERE ADMPSTDAT=20130930

SELECT DISTINCT ADMPSTDAT, AG.AGMPSTDAT
FROM dbo.SalesTier1YTD_BU D
INNER JOIN AGR AG on AG.AGMCLICOD=D.ADMCLICOD AND AG.AGMACCCOD=D.ADMACCCOD and AG.AGMAGRCOD=D.ADMAGRCOD and AG.AGMAGRSFX=D.ADMAGRSFX
WHERE ADMPSTDAT=20130930



Select * from AGR2 WHERE ADMPSTDAT<>AGMPSTDAT AND ADMPSTDAT=20130830
Select * from SalesTier1YTD_BU WHERE ADMPSTDAT<>AGMPSTDAT AND ADMPSTDAT=20130830
Select * from dbo.SAL002_Tier1_Sales_YTD WHERE ADMPSTDAT<>AGMPSTDAT AND ADMPSTDAT=20130830



